version: "3.8"

services:
  db:
    container_name: mong-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=transaction
      - MONGO_INIT_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

