server:
  port: 8082
spring:
  application:
    name: transaction-svc
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: transaction
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      auto-offset-reset: latest
      enable-auto-commit: true

management:
  endpoints:
    web:
      exposure:
        include: health, beans

transaction:
  validation:
    enabled: true
    banco: true
    horario: true


app:
  consumeTopic: transaction
  returnTopic: transaction_validate